[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = true  # Skip linting for faster builds

[programs.localnet]
solana_test_project = "48BYj4BVCp7D3EByu6f9nW8uHaFuuFdwJozB7iLZPxhJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[hooks]
