[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = true  # Skip linting for faster builds

[programs.localnet]
solana_test_project = "J2EkyNbg97YGxqdihVxe2Ey5AEBcR7QbA97JVpR4R4D8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[hooks]
