[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = true  # Skip linting for faster builds

[programs.localnet]
solana_test_project = "9ZCe7W3w8Fvi2KWaX9161sa3ZwmWLZj8EzXFyYMdQbNq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[hooks]
